import Head from 'next/head'
import HeroMobile from '../components/mobile/HeroMobile'
import HeroDekstop from '../components/dekstop/HeroDekstop'
import Body1Mobile from '../components/mobile/Body1Mobile'
import Body1Dekstop from '../components/dekstop/Body1Dekstop'
import Body2 from '../components/Body2'
import Body3 from '../components/Body3'
import Body4 from '../components/Body4'
import Body5Mobile from '../components/mobile/Body5Mobile'
import Body5Dekstop from '../components/dekstop/Body5Dekstop'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <>
      <Head>
      <title>Frontend Mentor | Sunnyside agency landing page</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" type="image/png" sizes="32x32" href="./favicon-32x32.png"/>
      </Head>
      <HeroMobile />
      <HeroDekstop />
      <Body1Mobile />
      <Body1Dekstop />
      <Body2 />
      <Body3 />
      <Body4 />
      <Body5Mobile />
      <Body5Dekstop />
      <Footer />
    </>
  )
}
